---
label: products
hide_body: true
fields:
- name: id
  type: text
  config:
    required: false
  label: id
- name: name
  type: text
  config:
    required: false
  label: name
- name: description
  type: text
  config:
    required: false
  label: description
- name: image
  type: text
  config:
    required: false
  label: image
- name: product_url
  type: text
  config:
    required: false
  label: product_url
pages:
- content/products/anotherthing.md
- content/products/fakeproduct.md
- content/products/thingthefourth.md
- content/products/thirdthing.md
